import { reactive } from 'vue'

export const coloumsFood = reactive<any>([
  { title: 'อาหาร' },
  { title: 'หมวดหมู่' },
  { title: 'ราคา' },
  { title: 'จำนวน' },
  { title: 'สถานะ' },
  { title: 'จัดการ' },
])

export const coloumsCategory = reactive<any>([
  { title: 'หมวดหมู่' },
  { title: 'จัดการ' },
])

export const coloumsEmployees = reactive<any>([
  { title: 'ชื่อ-สกุล' },
  { title: 'ตำแหน่ง' },
  { title: 'จัดการ' },
])

export const category = reactive([
  { id: 1, name: 'เครื่องดื่ม', img: '' },
  { id: 2, name: 'อาหาร', img: '' },
  { id: 3, name: 'แกง', img: '' },
  { id: 4, name: 'ของหวาน', img: '' },
])

export const foods = reactive<any>([
  {
    id: 1,
    name: 'น้ำเปล่า',
    category: 'เครื่องดื่ม',
    price: 10,
    qty: 999,
    img: 'https://ocs-k8s-prod.s3.ap-southeast-1.amazonaws.com/MENU_1603791069395.jpeg',
    isActive: true,
  },
  {
    id: 2,
    name: 'น้ำโค้ก',
    category: 'เครื่องดื่ม',
    price: 20,
    qty: 999,
    img: 'https://static.bigc.co.th/media/catalog/product/cache/2/image/17f82f742ffe127f42dca9de82fb58b1/8/8/8851959132012_7.jpg',
    isActive: true,
  },
  {
    id: 3,
    name: 'เนื้อ',
    category: 'อาหาร',
    price: 1000,
    qty: 999,
    img: 'https://ed.edtfiles-media.com/ud/news/1/155/463477/1_5-850x567.jpg',
    isActive: true,
  },
  {
    id: 4,
    name: 'ซูชิ',
    category: 'อาหาร',
    price: 50,
    qty: 999,
    img: 'http://d20aeo683mqd6t.cloudfront.net/th/articles/title_images/000/038/184/medium/sushi.jpg?2019',
    isActive: true,
  },
  {
    id: 5,
    name: 'ซูชิ',
    category: 'อาหาร',
    price: 100,
    qty: 999,
    img: 'http://d20aeo683mqd6t.cloudfront.net/th/articles/title_images/000/038/184/medium/sushi.jpg?2019',
    isActive: true,
  },
  {
    id: 6,
    name: 'ก๋วยเตี๋ยว',
    category: 'อาหาร',
    price: 50,
    qty: 999,
    img: '',
    isActive: true,
  },
  {
    id: 7,
    name: 'ส้มตำ',
    category: 'อาหาร',
    price: 50,
    qty: 999,
    img: '',
    isActive: false,
  },
  {
    id: 8,
    name: 'ข้าวมันไก่',
    category: 'อาหาร',
    price: 50,
    qty: 999,
    img: '',
    isActive: true,
  },
  {
    id: 9,
    name: 'ผัดไทย',
    category: 'อาหาร',
    price: 50,
    qty: 999,
    img: '',
    isActive: true,
  },
  {
    id: 10,
    name: 'แกงเขียวหวาน',
    category: 'แกง',
    price: 50,
    qty: 999,
    img: '',
    isActive: true,
  },
  {
    id: 11,
    name: 'พิซซ่า',
    category: 'อาหาร',
    price: 50,
    qty: 999,
    img: '',
    isActive: true,
  },
  {
    id: 12,
    name: 'เฟรนช์ฟรายส์',
    category: 'ของหวาน',
    price: 50,
    qty: 999,
    img: '',
    isActive: true,
  },
  {
    id: 13,
    name: 'ซูชิ',
    category: 'อาหาร',
    price: 50,
    qty: 999,
    img: '',
    isActive: false,
  },
  {
    id: 14,
    name: 'สปาเกตตี้',
    category: 'อาหาร',
    price: 50,
    qty: 999,
    img: '',
    isActive: true,
  },
  {
    id: 15,
    name: 'แซนด์วิช',
    category: 'ของหวาน',
    price: 50,
    qty: 999,
    img: '',
    isActive: true,
  },
  {
    id: 16,
    name: 'ขนมปัง',
    category: 'ของหวาน',
    price: 50,
    qty: 999,
    img: '',
    isActive: true,
  },
  {
    id: 17,
    name: 'โดนัท',
    category: 'ของหวาน',
    price: 50,
    qty: 999,
    img: '',
    isActive: true,
  },
  {
    id: 18,
    name: 'เค้ก',
    category: 'ของหวาน',
    price: 50,
    qty: 999,
    img: '',
    isActive: false,
  },
  {
    id: 19,
    name: 'บัวลอย',
    category: 'ของหวาน',
    price: 50,
    qty: 999,
    img: '',
    isActive: true,
  },
  {
    id: 20,
    name: 'ข้าวผัดหมู',
    category: 'อาหาร',
    price: 50,
    qty: 999,
    img: '',
    isActive: true,
  },
  {
    id: 21,
    name: 'asdasjjbaksfajasdbahjsdbjasf',
    category: 'ไม่ระบุบ',
    price: 50,
    qty: 999,
    img: '',
    isActive: false,
  },
])
